coverage:
  status:
    project:
      default:
        enabled: no

ignore:
  - "github.com/tim-hardcastle/pipefish/source/compiler/compiler_test.go"
  - "github.com/tim-hardcastle/pipefish/source/dtypes/dtypes_test.go"
  - "github.com/tim-hardcastle/pipefish/source/err/err_test.go"
  - "github.com/tim-hardcastle/pipefish/source/hub/hub_test.go"
  - "github.com/tim-hardcastle/pipefish/source/initializer/initializer_test.go"
  - "github.com/tim-hardcastle/pipefish/source/lexer/lexer_test.go"
  - "github.com/tim-hardcastle/pipefish/source/lexer/relexer_test.go"
  - "github.com/tim-hardcastle/pipefish/source/parser/parser_test.go"
  - "github.com/tim-hardcastle/pipefish/source/pf/pf_test.go"
  - "github.com/tim-hardcastle/pipefish/source/test_helper/test_helper_test.go"
  - "github.com/tim-hardcastle/pipefish/source/text/text_test.go"
  - "github.com/tim-hardcastle/pipefish/source/values/values_test.go"
  - "github.com/tim-hardcastle/pipefish/source/vm/vm_test.go"
