coverage:
  status:
    project:
      default:
        enabled: no

ignore:
  - "source/compiler/compiler_test.go"
  - "source/dtypes/dtypes_test.go"
  - "source/err/err_test.go"
  - "source/hub/hub_test.go"
  - "source/initializer/initializer_test.go"
  - "source/lexer/lexer_test.go"
  - "source/lexer/relexer_test.go"
  - "source/parser/parser_test.go"
  - "source/pf/pf_test.go"
  - "source/test_helper/test_helper_test.go"
  - "source/text/text_test.go"
  - "source/values/values_test.go"
  - "source/vm/vm_test.go"
